# escape=`

FROM mcr.microsoft.com/powershell:nanoserver-ltsc2022

RUN `
  mkdir tmp && mkdir git`
	&& curl -sSfLo tmp/file.zip https://github.com/git-for-windows/git/releases/download/v2.38.1.windows.1/MinGit-2.38.1-64-bit.zip `
  && tar -C c:\git -oxzf tmp/file.zip`
  && rmdir /Q /S tmp

RUN `
  mkdir tmp`
  && curl -sSfLo tmp/file.zip https://github.com/git-lfs/git-lfs/releases/download/v3.2.0/git-lfs-windows-amd64-v3.2.0.zip `
  && tar -C c:\git\usr\bin -oxzf tmp/file.zip`
  && rmdir /Q /S tmp

RUN setx PATH "%PATH%;/git/cmd;/git/mingw64/bin;/git/usr/bin"

ADD windows/* /bin/

CMD ["pwsh", "/bin/clone.ps1"]
